name: Publish Docker Image to Docker Hub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish_image:

    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: hansonhschang/ros2-vicon

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: hansonhschang
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
        docker tag ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }} ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:latest
  