name: Publish Docker Image to Docker Hub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish_image:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [ "hansonhschang/ros2-vicon:$(date +%s)" ]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ matrix.image-name }}
    - name: Publish the Docker image to Docker Hub
      run: |
        docker login -u hansonhschang -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ matrix.image-name }}
